<h1>Logistic Regression</h1>

In [14]:
import pandas as pd 
import seaborn as sns 
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, precision_score #evaluation matrix
from sklearn.metrics import confusion_matrix # evaluation matrix

In [15]:
df = pd.read_csv("1-heart.csv")

df.columns
df.info()
df.isnull().sum()
df.nunique()
df["target"].nunique() # 2 values hai ya to 0 hoga ya to 1 hoga

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 303 entries, 0 to 302
Data columns (total 14 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   age       303 non-null    int64
 1   sex       303 non-null    int64
 2   cp        303 non-null    int64
 3   trestbps  303 non-null    int64
 4   chol      303 non-null    int64
 5   fbs       303 non-null    int64
 6   restecg   303 non-null    int64
 7   thalach   303 non-null    int64
 8   exang     303 non-null    int64
 9   oldpeak   303 non-null    float64
 10  slope     303 non-null    int64
 11  ca        303 non-null    int64
 12  thal      303 non-null    int64
 13  target    303 non-null    int64
dtypes: float64(1), int64(13)
memory usage: 33.3 KB

2

In [16]:
df.head()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,63,1,3,145,233,1,0,150,0,2.3,0,0,1,1
1,37,1,2,130,250,0,1,187,0,3.5,0,0,2,1
2,41,0,1,130,204,0,0,172,0,1.4,2,0,2,1
3,56,1,1,120,236,0,1,178,0,0.8,2,0,2,1
4,57,0,0,120,354,0,1,163,1,0.6,2,0,2,1

In [20]:
X=df.drop(columns=["target"], axis=1)
y=df["target"] 
X.head()
#y.head()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal
0,63,1,3,145,233,1,0,150,0,2.3,0,0,1
1,37,1,2,130,250,0,1,187,0,3.5,0,0,2
2,41,0,1,130,204,0,0,172,0,1.4,2,0,2
3,56,1,1,120,236,0,1,178,0,0.8,2,0,2
4,57,0,0,120,354,0,1,163,1,0.6,2,0,2

In [23]:
# Train-Test split 
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.33, random_state=42)

In [25]:
model = LogisticRegression(max_iter=1000)
model.fit(X_train, y_train)

LogisticRegression(max_iter=1000)

In [27]:
#predicted
y_pred = model.predict(X_test)
print(y_pred)

[0 1 1 0 1 1 1 0 0 0 1 0 1 0 1 1 1 0 0 0 1 0 0 1 1 1 1 1 0 1 0 0 0 0 1 0 1
 1 1 1 0 1 1 1 1 0 1 1 0 0 0 0 1 1 0 0 0 1 0 0 0 1 0 1 1 0 1 1 1 1 1 1 1 1
 0 1 1 1 0 0 0 0 1 1 1 0 0 1 0 0 1 1 1 1 1 0 1 0 1 0]

In [34]:
#actual value 
y_test

179    0
228    0
111    1
246    0
60     1
      ..
163    1
155    1
97     1
68     1
229    0
Name: target, Length: 100, dtype: int64

In [33]:
# accuracy find kri hai actual or predicted value ki 
print("accuracy: ", accuracy_score(y_test, y_pred)*100,"%")
print("accuracy: ", precision_score(y_test, y_pred)*100,"%")

accuracy:  80.0 %
accuracy:  83.92857142857143 %

In [ ]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [35]:
X_train

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal
37,54,1,2,150,232,0,0,165,0,1.6,2,0,3
16,58,0,2,120,340,0,1,172,0,0.0,2,0,2
126,47,1,0,112,204,0,1,143,0,0.1,2,0,2
291,58,1,0,114,318,0,2,140,0,4.4,0,3,1
273,58,1,0,100,234,0,1,156,0,0.1,2,1,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...
188,50,1,2,140,233,0,1,163,0,0.6,1,1,3
71,51,1,2,94,227,0,1,154,1,0.0,2,1,3
106,69,1,3,160,234,1,0,131,0,0.1,1,1,2
270,46,1,0,120,249,0,0,144,0,0.8,2,0,3
102,63,0,1,140,195,0,1,179,0,0.0,2,2,2

In [39]:
# evaluation matrix (confusion matrix)
from sklearn.metrics import confusion_matrix

cm = confusion_matrix(y_test, y_pred)
print(cm) 
# 33+47=80
# 9+11=20 , 20 value ke liye wrong predict kiya hai baki majority sahi hai 80

[[33  9]
 [11 47]]

In [38]:
model.fit(X_train, y_train) 
y_pred = model.predict(X_test)
#print(y_pred) 
print("accuracy: ", accuracy_score(y_test, y_pred)*100,"%")
print("accuracy: ", precision_score(y_test, y_pred)*100,"%")

accuracy:  80.0 %
accuracy:  83.92857142857143 %

In [ ]:
# Confusion Matrix
#      ↓
# Accuracy : 
#      ↓
# Precision : 
#      ↓
# Recall
#      ↓
# F1 Score